environment: false

port: :3000

cors:
  - http://example.com

jwt_secret: hello

db: host=example.com user=db_user password=db_password dbname=db_name port=1234 sslmode=disable connect_timeout=5 TimeZone=Asia/Bangkok
