environment: false

port: :3000

cors:
  - http://example.com

jwt_secret: hello

postgres: host=example.com user=db_user password=db_password dbname=db_name port=1234 sslmode=disable connect_timeout=5 TimeZone=Asia/Bangkok

mongo: mongodb://certapp_user:secure_password@localhost:27017/certificate_app

mongo_database: certificate_app

renderer_url: http://example.com