environment: false

port: :3000

backend_url: http://localhost:3000

cors:
  - http://example.com

jwt_secret: hello

postgres: host=example.com user=db_user password=db_password dbname=db_name port=1234 sslmode=disable connect_timeout=5 TimeZone=Asia/Bangkok

mongo: mongodb://certapp_user:secure_password@localhost:27017/certificate_app

mongo_database: certificate_app

verify_host: http://example.com

minio_endpoint: http://minio.sit.kmutt.ac.th

minio_access_key: access

minio_secret_key: private

bucket_resource: bucket_resource

bucket_certificate: bucket_certificate

sso_issuer_url: http:sso.com

sso_client: client

sso_secret: secret

mail_host: smtp.com

mail_user: mail@com

mail_pass: securepass

signing_enabled: true

signing_cert_path: certs/signing-cert.pem

signing_key_path: certs/signing-key.pem