ervices:
  backend-api:
    build:
      context: ./easy-cert-api
      dockerfile: dockerfile
    container_name: easy-cert-api
    restart: unless-stopped
    networks:
      # - scholar-network
      - reverseproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easy-cert-api.rule=Host(`easy-cert-api.sunthewhat.com`)"
      - "traefik.http.routers.easy-cert-api.entrypoints=websecure"
      - "traefik.http.routers.easy-cert-api.tls=true"
      - "traefik.http.routers.easy-cert-api.tls.certresolver=myresolver"
      - "traefik.http.services.easy-cert-api.loadbalancer.server.port=8000"
    # depends_on:
    #   - mongodb
    #   - storage-service


# volumes:
#   mongodb_data:
#     driver: local
#   mongodb_config:
#     driver: local
#   storage_uploads:
#     driver: local

networks:
  # scholar-network:
  #   driver: bridge
  reverseproxy:
    external: true
    name: reverseproxy