// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sunthewhat/secure-docs-api/type/shared/model"
)

func newCertificate(db *gorm.DB, opts ...gen.DOOption) certificate {
	_certificate := certificate{}

	_certificate.certificateDo.UseDB(db, opts...)
	_certificate.certificateDo.UseModel(&model.Certificate{})

	tableName := _certificate.certificateDo.TableName()
	_certificate.ALL = field.NewAsterisk(tableName)
	_certificate.ID = field.NewString(tableName, "id")
	_certificate.Name = field.NewString(tableName, "name")
	_certificate.Design = field.NewString(tableName, "design")
	_certificate.UserID = field.NewString(tableName, "user_id")
	_certificate.CreatedAt = field.NewTime(tableName, "created_at")
	_certificate.UpdatedAt = field.NewTime(tableName, "updated_at")

	_certificate.fillFieldMap()

	return _certificate
}

type certificate struct {
	certificateDo

	ALL       field.Asterisk
	ID        field.String
	Name      field.String
	Design    field.String
	UserID    field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c certificate) Table(newTableName string) *certificate {
	c.certificateDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c certificate) As(alias string) *certificate {
	c.certificateDo.DO = *(c.certificateDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *certificate) updateTableName(table string) *certificate {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Name = field.NewString(table, "name")
	c.Design = field.NewString(table, "design")
	c.UserID = field.NewString(table, "user_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *certificate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *certificate) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["design"] = c.Design
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c certificate) clone(db *gorm.DB) certificate {
	c.certificateDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c certificate) replaceDB(db *gorm.DB) certificate {
	c.certificateDo.ReplaceDB(db)
	return c
}

type certificateDo struct{ gen.DO }

func (c certificateDo) Debug() *certificateDo {
	return c.withDO(c.DO.Debug())
}

func (c certificateDo) WithContext(ctx context.Context) *certificateDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c certificateDo) ReadDB() *certificateDo {
	return c.Clauses(dbresolver.Read)
}

func (c certificateDo) WriteDB() *certificateDo {
	return c.Clauses(dbresolver.Write)
}

func (c certificateDo) Session(config *gorm.Session) *certificateDo {
	return c.withDO(c.DO.Session(config))
}

func (c certificateDo) Clauses(conds ...clause.Expression) *certificateDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c certificateDo) Returning(value interface{}, columns ...string) *certificateDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c certificateDo) Not(conds ...gen.Condition) *certificateDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c certificateDo) Or(conds ...gen.Condition) *certificateDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c certificateDo) Select(conds ...field.Expr) *certificateDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c certificateDo) Where(conds ...gen.Condition) *certificateDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c certificateDo) Order(conds ...field.Expr) *certificateDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c certificateDo) Distinct(cols ...field.Expr) *certificateDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c certificateDo) Omit(cols ...field.Expr) *certificateDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c certificateDo) Join(table schema.Tabler, on ...field.Expr) *certificateDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c certificateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *certificateDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c certificateDo) RightJoin(table schema.Tabler, on ...field.Expr) *certificateDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c certificateDo) Group(cols ...field.Expr) *certificateDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c certificateDo) Having(conds ...gen.Condition) *certificateDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c certificateDo) Limit(limit int) *certificateDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c certificateDo) Offset(offset int) *certificateDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c certificateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *certificateDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c certificateDo) Unscoped() *certificateDo {
	return c.withDO(c.DO.Unscoped())
}

func (c certificateDo) Create(values ...*model.Certificate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c certificateDo) CreateInBatches(values []*model.Certificate, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c certificateDo) Save(values ...*model.Certificate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c certificateDo) First() (*model.Certificate, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) Take() (*model.Certificate, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) Last() (*model.Certificate, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) Find() ([]*model.Certificate, error) {
	result, err := c.DO.Find()
	return result.([]*model.Certificate), err
}

func (c certificateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Certificate, err error) {
	buf := make([]*model.Certificate, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c certificateDo) FindInBatches(result *[]*model.Certificate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c certificateDo) Attrs(attrs ...field.AssignExpr) *certificateDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c certificateDo) Assign(attrs ...field.AssignExpr) *certificateDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c certificateDo) Joins(fields ...field.RelationField) *certificateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c certificateDo) Preload(fields ...field.RelationField) *certificateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c certificateDo) FirstOrInit() (*model.Certificate, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) FirstOrCreate() (*model.Certificate, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) FindByPage(offset int, limit int) (result []*model.Certificate, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c certificateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c certificateDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c certificateDo) Delete(models ...*model.Certificate) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *certificateDo) withDO(do gen.Dao) *certificateDo {
	c.DO = *do.(*gen.DO)
	return c
}
