// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sunthewhat/easy-cert-api/type/shared/model"
)

func newParticipant(db *gorm.DB, opts ...gen.DOOption) participant {
	_participant := participant{}

	_participant.participantDo.UseDB(db, opts...)
	_participant.participantDo.UseModel(&model.Participant{})

	tableName := _participant.participantDo.TableName()
	_participant.ALL = field.NewAsterisk(tableName)
	_participant.ID = field.NewString(tableName, "id")
	_participant.CertificateID = field.NewString(tableName, "certificate_id")
	_participant.Isrevoke = field.NewBool(tableName, "isrevoke")
	_participant.CreatedAt = field.NewTime(tableName, "created_at")
	_participant.UpdatedAt = field.NewTime(tableName, "updated_at")

	_participant.fillFieldMap()

	return _participant
}

type participant struct {
	participantDo

	ALL           field.Asterisk
	ID            field.String
	CertificateID field.String
	Isrevoke      field.Bool
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (p participant) Table(newTableName string) *participant {
	p.participantDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p participant) As(alias string) *participant {
	p.participantDo.DO = *(p.participantDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *participant) updateTableName(table string) *participant {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.CertificateID = field.NewString(table, "certificate_id")
	p.Isrevoke = field.NewBool(table, "isrevoke")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *participant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *participant) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["certificate_id"] = p.CertificateID
	p.fieldMap["isrevoke"] = p.Isrevoke
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p participant) clone(db *gorm.DB) participant {
	p.participantDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p participant) replaceDB(db *gorm.DB) participant {
	p.participantDo.ReplaceDB(db)
	return p
}

type participantDo struct{ gen.DO }

func (p participantDo) Debug() *participantDo {
	return p.withDO(p.DO.Debug())
}

func (p participantDo) WithContext(ctx context.Context) *participantDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p participantDo) ReadDB() *participantDo {
	return p.Clauses(dbresolver.Read)
}

func (p participantDo) WriteDB() *participantDo {
	return p.Clauses(dbresolver.Write)
}

func (p participantDo) Session(config *gorm.Session) *participantDo {
	return p.withDO(p.DO.Session(config))
}

func (p participantDo) Clauses(conds ...clause.Expression) *participantDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p participantDo) Returning(value interface{}, columns ...string) *participantDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p participantDo) Not(conds ...gen.Condition) *participantDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p participantDo) Or(conds ...gen.Condition) *participantDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p participantDo) Select(conds ...field.Expr) *participantDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p participantDo) Where(conds ...gen.Condition) *participantDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p participantDo) Order(conds ...field.Expr) *participantDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p participantDo) Distinct(cols ...field.Expr) *participantDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p participantDo) Omit(cols ...field.Expr) *participantDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p participantDo) Join(table schema.Tabler, on ...field.Expr) *participantDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p participantDo) LeftJoin(table schema.Tabler, on ...field.Expr) *participantDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p participantDo) RightJoin(table schema.Tabler, on ...field.Expr) *participantDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p participantDo) Group(cols ...field.Expr) *participantDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p participantDo) Having(conds ...gen.Condition) *participantDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p participantDo) Limit(limit int) *participantDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p participantDo) Offset(offset int) *participantDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p participantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *participantDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p participantDo) Unscoped() *participantDo {
	return p.withDO(p.DO.Unscoped())
}

func (p participantDo) Create(values ...*model.Participant) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p participantDo) CreateInBatches(values []*model.Participant, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p participantDo) Save(values ...*model.Participant) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p participantDo) First() (*model.Participant, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Participant), nil
	}
}

func (p participantDo) Take() (*model.Participant, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Participant), nil
	}
}

func (p participantDo) Last() (*model.Participant, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Participant), nil
	}
}

func (p participantDo) Find() ([]*model.Participant, error) {
	result, err := p.DO.Find()
	return result.([]*model.Participant), err
}

func (p participantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Participant, err error) {
	buf := make([]*model.Participant, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p participantDo) FindInBatches(result *[]*model.Participant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p participantDo) Attrs(attrs ...field.AssignExpr) *participantDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p participantDo) Assign(attrs ...field.AssignExpr) *participantDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p participantDo) Joins(fields ...field.RelationField) *participantDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p participantDo) Preload(fields ...field.RelationField) *participantDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p participantDo) FirstOrInit() (*model.Participant, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Participant), nil
	}
}

func (p participantDo) FirstOrCreate() (*model.Participant, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Participant), nil
	}
}

func (p participantDo) FindByPage(offset int, limit int) (result []*model.Participant, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p participantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p participantDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p participantDo) Delete(models ...*model.Participant) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *participantDo) withDO(do gen.Dao) *participantDo {
	p.DO = *do.(*gen.DO)
	return p
}
