// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sunthewhat/easy-cert-api/type/shared/model"
)

func newSigner(db *gorm.DB, opts ...gen.DOOption) signer {
	_signer := signer{}

	_signer.signerDo.UseDB(db, opts...)
	_signer.signerDo.UseModel(&model.Signer{})

	tableName := _signer.signerDo.TableName()
	_signer.ALL = field.NewAsterisk(tableName)
	_signer.ID = field.NewString(tableName, "id")
	_signer.Email = field.NewString(tableName, "email")
	_signer.DisplayName = field.NewString(tableName, "display_name")
	_signer.CreatedAt = field.NewTime(tableName, "created_at")
	_signer.CreatedBy = field.NewString(tableName, "created_by")

	_signer.fillFieldMap()

	return _signer
}

type signer struct {
	signerDo

	ALL         field.Asterisk
	ID          field.String
	Email       field.String
	DisplayName field.String
	CreatedAt   field.Time
	CreatedBy   field.String

	fieldMap map[string]field.Expr
}

func (s signer) Table(newTableName string) *signer {
	s.signerDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s signer) As(alias string) *signer {
	s.signerDo.DO = *(s.signerDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *signer) updateTableName(table string) *signer {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.Email = field.NewString(table, "email")
	s.DisplayName = field.NewString(table, "display_name")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.CreatedBy = field.NewString(table, "created_by")

	s.fillFieldMap()

	return s
}

func (s *signer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *signer) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["email"] = s.Email
	s.fieldMap["display_name"] = s.DisplayName
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["created_by"] = s.CreatedBy
}

func (s signer) clone(db *gorm.DB) signer {
	s.signerDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s signer) replaceDB(db *gorm.DB) signer {
	s.signerDo.ReplaceDB(db)
	return s
}

type signerDo struct{ gen.DO }

func (s signerDo) Debug() *signerDo {
	return s.withDO(s.DO.Debug())
}

func (s signerDo) WithContext(ctx context.Context) *signerDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s signerDo) ReadDB() *signerDo {
	return s.Clauses(dbresolver.Read)
}

func (s signerDo) WriteDB() *signerDo {
	return s.Clauses(dbresolver.Write)
}

func (s signerDo) Session(config *gorm.Session) *signerDo {
	return s.withDO(s.DO.Session(config))
}

func (s signerDo) Clauses(conds ...clause.Expression) *signerDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s signerDo) Returning(value interface{}, columns ...string) *signerDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s signerDo) Not(conds ...gen.Condition) *signerDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s signerDo) Or(conds ...gen.Condition) *signerDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s signerDo) Select(conds ...field.Expr) *signerDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s signerDo) Where(conds ...gen.Condition) *signerDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s signerDo) Order(conds ...field.Expr) *signerDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s signerDo) Distinct(cols ...field.Expr) *signerDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s signerDo) Omit(cols ...field.Expr) *signerDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s signerDo) Join(table schema.Tabler, on ...field.Expr) *signerDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s signerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *signerDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s signerDo) RightJoin(table schema.Tabler, on ...field.Expr) *signerDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s signerDo) Group(cols ...field.Expr) *signerDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s signerDo) Having(conds ...gen.Condition) *signerDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s signerDo) Limit(limit int) *signerDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s signerDo) Offset(offset int) *signerDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s signerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *signerDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s signerDo) Unscoped() *signerDo {
	return s.withDO(s.DO.Unscoped())
}

func (s signerDo) Create(values ...*model.Signer) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s signerDo) CreateInBatches(values []*model.Signer, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s signerDo) Save(values ...*model.Signer) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s signerDo) First() (*model.Signer, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Signer), nil
	}
}

func (s signerDo) Take() (*model.Signer, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Signer), nil
	}
}

func (s signerDo) Last() (*model.Signer, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Signer), nil
	}
}

func (s signerDo) Find() ([]*model.Signer, error) {
	result, err := s.DO.Find()
	return result.([]*model.Signer), err
}

func (s signerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Signer, err error) {
	buf := make([]*model.Signer, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s signerDo) FindInBatches(result *[]*model.Signer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s signerDo) Attrs(attrs ...field.AssignExpr) *signerDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s signerDo) Assign(attrs ...field.AssignExpr) *signerDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s signerDo) Joins(fields ...field.RelationField) *signerDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s signerDo) Preload(fields ...field.RelationField) *signerDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s signerDo) FirstOrInit() (*model.Signer, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Signer), nil
	}
}

func (s signerDo) FirstOrCreate() (*model.Signer, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Signer), nil
	}
}

func (s signerDo) FindByPage(offset int, limit int) (result []*model.Signer, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s signerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s signerDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s signerDo) Delete(models ...*model.Signer) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *signerDo) withDO(do gen.Dao) *signerDo {
	s.DO = *do.(*gen.DO)
	return s
}
