// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCertificate = "certificates"

// Certificate mapped from table <certificates>
type Certificate struct {
	ID           string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Design       string    `gorm:"column:design;not null" json:"design"`
	UserID       string    `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	ThumbnailURL string    `gorm:"column:thumbnail_url" json:"thumbnail_url"`
}

// TableName Certificate's table name
func (*Certificate) TableName() string {
	return TableNameCertificate
}
