// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGraphic = "graphics"

// Graphic mapped from table <graphics>
type Graphic struct {
	ID         string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	SvgContent string    `gorm:"column:svg_content;not null" json:"svg_content"`
	UserID     string    `gorm:"column:user_id;not null" json:"userId"`
	User       User      `gorm:"foreignKey:UserID;references:ID"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName Graphic's table name
func (*Graphic) TableName() string {
	return TableNameGraphic
}
