// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameParticipant = "participants"

// Participant mapped from table <participants>
type Participant struct {
	ID             string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	CertificateID  string    `gorm:"column:certificate_id;not null" json:"certificate_id"`
	Isrevoke       bool      `gorm:"column:isrevoke;not null" json:"isrevoke"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	CertificateURL string    `gorm:"column:certificate_url" json:"certificate_url"`
	EmailStatus    string    `gorm:"column:email_status;not null;default:pending" json:"email_status"`
	IsDownloaded   bool      `gorm:"column:is_downloaded;not null" json:"is_downloaded"`
}

// TableName Participant's table name
func (*Participant) TableName() string {
	return TableNameParticipant
}
