// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSigner = "signers"

// Signer mapped from table <signers>
type Signer struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	DisplayName string    `gorm:"column:display_name;not null" json:"display_name"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	CreatedBy   string    `gorm:"column:created_by;not null" json:"created_by"`
}

// TableName Signer's table name
func (*Signer) TableName() string {
	return TableNameSigner
}
