// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSignature = "signatures"

// Signature mapped from table <signatures>
type Signature struct {
	ID            string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	SignerID      string    `gorm:"column:signer_id;not null" json:"signer_id"`
	CertificateID string    `gorm:"column:certificate_id;not null" json:"certificate_id"`
	Signature     string    `gorm:"column:signature;not null" json:"signature"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	IsSigned      bool      `gorm:"column:is_signed;not null" json:"is_signed"`
	CreatedBy     string    `gorm:"column:created_by;not null" json:"created_by"`
}

// TableName Signature's table name
func (*Signature) TableName() string {
	return TableNameSignature
}
